"""empty message

Revision ID: 737f9ceeddc8
Revises: 
Create Date: 2026-04-30 22:24:18.138327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737f9ceeddc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.alter_column('google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
