"""make name as optional in dbconnection

Revision ID: 817332adb0b9
Revises: 737f9ceeddc8
Create Date: 2026-05-10 17:47:15.513292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817332adb0b9'
down_revision = '737f9ceeddc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_connections', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
